### ISSUE TITLE
How does this relate to dhcpVol

### ISSUE THREAD

**Issue by oesteban** [templateflow/tpl-dhcpSym#1]
How does this relate to @tsalo's https://gin.g-node.org/tsalo/tpl-dhcpVol/?

**Comment by tsalo** [comment]
This is the symmetrical surface templates from the same project as tpl-dhcpVol (which is the volumetric templates), but different papers and potentially samples within the dHCP project.

**Comment by tsalo** [comment]
@mgxd is working on the older, asymmetrical surface templates (`tpl-dhcpAsym`) as well.

EDIT: lol he just pushed that one to https://github.com/templateflow/tpl-dhcpAsym
